[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "resume-agent"
version = "0.1.0"
description = "An agent that formulates and writes a resume from user-described experience and skills."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Your Name" }]
dependencies = [
  "jinja2>=3.1",
]

[project.scripts]
resume-agent = "resume_agent.cli:main"
